theme = "kanagawa"

[editor.terminal]
command = "footclient"
args = [ "sh", "-c" ]

[editor.cursor-shape]
insert = "bar"

[keys.normal]
"X" = ["extend_line_up", "extend_to_line_bounds"]

[keys.normal."space"]
"F" = "file_picker_in_current_buffer_directory"

[keys.select]
"X" = ["extend_line_up", "extend_to_line_bounds"]
